name: build

on:
  workflow_dispatch:
    concurrency:
      group: ubuntu-iso-build
      cancel-in-progress: true

jobs:
  build_and_upload:
    name: Build ISO and Upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        descriptor: ["ubuntu-kinetic-2.2.0"]
        include:
          - descriptor: "ubuntu-kinetic-2.2.0"
            config-file: regolith-2_2-mantic-config.sh
    steps:
      - uses: actions/checkout@v3
      - name: Build ISO
        run: |
          cd scripts
          mv ${{ matrix.config-file }} default_config.sh
          ./build.sh -
          cd ..
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: regolith-${{ matrix.descriptor }}.iso
          path: scripts/Regolith.iso
