name: build-jammy

on:
  workflow_dispatch:
concurrency: 
  group: ubuntu-iso-build
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build ISO
        id: build-iso
        run: |
          cd scripts
          mv regolith-2_1-jammy-config.sh default_config.sh
          ./build.sh -
          cd ..
          mv scripts/Regolith.iso regolith-ubuntu-jammy-2.1.iso
          mv scripts/image/md5sum.txt regolith-ubuntu-jammy-2.1.md5sum
          echo ::set-output name=TIMESTAMP::"$(date +%Y%m%d_%H%M%S)"
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KAMATERA_SSH_KEY }}
      - name: Compress
        run: |
          zip regolith-ubuntu-jammy-2.1.zip regolith-ubuntu-jammy-2.1.iso regolith-ubuntu-jammy-2.1.md5sum
      - name: Deploy
        run: |
          ssh-keyscan -H ${{ secrets.KAMATERA_HOSTNAME }} >> ~/.ssh/known_hosts
          scp regolith-ubuntu-jammy-2.1.zip root@${{ secrets.KAMATERA_HOSTNAME }}:/var/www/html/isos/
      - uses: softprops/action-gh-release@v1
        with:
          body: See regolith-desktop.com for released files
          name: ISO Build ${{ steps.build-iso.outputs.TIMESTAMP }}
          tag_name: isobuild-${{ steps.build-iso.outputs.TIMESTAMP }}
          files: |
            regolith-ubuntu-jammy-2.1.zip